name: CI
on:
  pull_request:
    branches:
      - develop
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull our code from the current repo and branch
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{runner.os}}-node-
      - name: Install specific nodejs version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - name: format check
        run: npm run format:check
      # - name: format code
      #   run: npm run format
      - name: generate coverage report
        run: npm test -- --coverage
        env:
          CI: true
      - name: upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Uplade build folder
        uses: actions/upload-artifacts@v1
        with:
          name: build
          path: build
      - name: Deploy to stagging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain wry-hot.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
